spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://mysql:3306/orders
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: inventory-group
      auto-offset-reset: earliest